### ISSUE TITLE
Downgrade silex version

### ISSUE THREAD

**Issue by agentsib** [e-Sixt/rabbitmq-service-provider#1]
Hello,  why it was necessary to raise up to 1.3 version of Silex?

**Comment by AntonStoeckl** [comment]
It's the latest stable minor in their 1.x.
Why could someone not upgrade from any 1.x version, it's compatible?!
I see no reason to start this with outdated dependencies.
What issue do you have with upgrading?

**Comment by agentsib** [comment]
For example, I have old project. I can update only this library, but I'm afraid update all packages in project. It's dangerous (no tests...).
Also, I think it is better to specify the minimum version which can run scripts.

Thanks for quick answer )

**Comment by AntonStoeckl** [comment]
I understand, but that's what semantic versioning is for!
1.x can be updated to 1.3.5 (latest stable Silex) without danger. For sure this means you need to trust Silex developers in some way. ;-)
You can easily do "composer update silex/silex" to not update other packages!
