### ISSUE TITLE
Silex 2.* compatible version

### ISSUE THREAD

**Issue by hiredgun** [e-Sixt/rabbitmq-service-provider#2]
Any plans regarding version compatible with Silex 2.\* ?

**Comment by williamespindola** [comment]
I think this change is a major release. Ca we take advantage of this release and fix namespace according PSR-4

**Comment by williamespindola** [comment]
ping

**Comment by AntonStoeckl** [comment]
Sorry for the late reply!
For a number of reasons, job and family related, I can't maintain this any more. :-(
I have abandoned the package on Packagist.
If anybody wants to fork and take over I can point to the replacement on Packagist.

**Comment by williamespindola** [comment]
Thanks @AntonStoeckl I can maintain it.
